org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.20.2)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.06.26-1.20.1
mod_id=gogaddon
archive_base_name=grimoireofgaia_addon-1.20.1
mod_name=Grimoire of Gaia 4 Addon
mod_license=LGPL-3.0
mod_group_id=net.sodiumzh.gogaddon
mod_authors=SodiumZH, Silentine
mod_description=An unofficial port of unimplemented mobs from Grimoire of Gaia 1.12.2.
jei_version=15.2.0.27
mixinextras_version=0.3.1
mixinextras_version_range=[0.3.0,)

mod_version=0.2.32
filename_version=0.2.32-dev

nfu_version=0.2.32
nfu_version_range=[0.2.32, 0.2.33)
gaia_version_range=[4.0.0-alpha.11, 5)